### ISSUE TITLE
Can't even get the example to work

### ISSUE THREAD

**Issue by reubenavery** [phramz/php-composer-repository-model#2]
Having zero luck getting any action from this.  Just running the example provided in the readme and docs/example1.php fails with `Error: Call to a member function getPackages() on a non-object`

I'm trying to work out the architecture of this package but having little to no luck understanding.  What's with all the abstraction?  I just want to be able to work with the data back-end behind a (private) Packagist or Satis repo server.  (But I can't even get it working with Packagist.org)

Working from this code from your example1.php:
```
echo $service
    // [packages.json]
    ->buildModel(
        'https://packagist.org',
        'packages.json'
    )
    // [packages.json][provider-includes]
    ->getProviderIncludes()
    // [packages.json][provider-includes][p/provider-archived$%hash%.json]
    ->get('p/provider-archived$%hash%.json')
    // [packages.json][provider-includes][p/provider-archived$0123456789.json][providers]
    ->getProviders()
    // [packages.json][provider-includes][...][providers][p/phramz/doctrine-annotation-scanner$0123456789.json]
    ->get("phramz/doctrine-annotation-scanner")
    // [packages.json][provider-includes][...][providers][...][packages]
    ->getPackages()
    // [packages.json][provider-includes][...][providers][...][packages][phramz/doctrine-annotation-scanner]
    ->first()
    // [packages.json][provider-includes][...][providers][...][packages][...][v1.0.0]
    ->last()
    // [packages.json][provider-includes][...][providers][...][packages][...][v1.0.0][source]
    ->getSource()
    // [packages.json][provider-includes][...][providers][...][packages][...][v1.0.0][source][url]
    ->getUrl();
```

**Comment by phramz** [comment]
well, yes ... the example is outdated because packagist changed the list of providers. try to use `p/provider-2013$%hash%.json` instead of `p/provider-archived$%hash%.json`.

thanks for reporting that issue.
